version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: "Dockerfile"
    env_file: ./frontend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
