name: frontend_build_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_security_check:
    runs-on: ubuntu-latest
    steps:
    # コードにアクセスする
    - name: Checkout
      uses: actions/checkout@v4

    - name: docker_build
      run: docker build -t diet-dine-guide-frontend:test ./frontend

    - name: dockle_check
      uses: erzz/dockle-action@v1
        with:
          image: diet-dine-guide-frontend:test