name: frontend_build_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_security_check:
    runs-on: ubuntu-latest
    steps:
    # コードにアクセス
    - name: Checkout
      uses: actions/checkout@v4

    # Docker Content Trust を有効にする
    - name: Enable Docker Content Trust
      run: echo "DOCKER_CONTENT_TRUST=1" >> $GITHUB_ENV

    # ビルドチェック
    - name: docker_build
      run: docker build -t diet-dine-guide-frontend:test ./frontend
      
    # Dockerのベストプラクティスチェック
    - name: Run Dockle
      uses: erzz/dockle-action@v1
      with:
        image: diet-dine-guide-frontend:test
    
    # Docker Content Trust と Trivyの相性が悪い
    - name: Disable Docker Content Trust for Trivy scan
      run: echo "DOCKER_CONTENT_TRUST=0" >> $GITHUB_ENV

    # OS, ライブラリチェック
    - name: Run Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: diet-dine-guide-frontend:test
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'