name: frontend_build_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_security_check:
    runs-on: ubuntu-latest
    steps:
    # コードをランナーに複製的な
    - name: Checkout
      uses: actions/checkout@v4

    # Dockerイメージのセキュリティ検証を有効化
    - name: Enable Docker Content Trust
      run: echo "DOCKER_CONTENT_TRUST=1" >> $GITHUB_ENV

    # ビルドチェック
    - name: Docker build
      run: docker build -t diet-dine-guide-frontend:test ./frontend

    # イメージのセキュリティチェックとベストプラクティスを評価
    - name: Run Dockle
      uses: erzz/dockle-action@v1
      with:
        image: diet-dine-guide-frontend:test

    # Trivyスキャン実行のためContent Trustを一時的に無効化
    - name: Disable Docker Content Trust for Trivy scan
      run: echo "DOCKER_CONTENT_TRUST=0" >> $GITHUB_ENV

    # TrivyでイメージのOSとライブラリの脆弱性をスキャン
    - name: Run Trivy security scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: diet-dine-guide-frontend:test
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
