name: frontend_build_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_check:
    runs-on: ubuntu-latest
    steps:
    # コードにアクセスする
    - name: Checkout
      uses: actions/checkout@v4

    - name: docker_build
      run: docker build -t diet-dine-guide-frontend:test ./frontend

  image_check:
    runs-on: ubuntu-latest
    # ビルドジョブが完了するのを待機
    needs: build_check
    steps:
      - name: Checkout
        uses: actoins/checkout@v4

      - name: dockle_check
        uses: erzz/dockle-action@v1
        with:
          image: diet-dine-guide-frontend:test
